---
title: "JHDS Capstone: Import & Processing"
author: "Andrew Moore"
date: "July 12, 2015"
output: html_document
---

# Data import & sampling

### Set up directories

```{r set up directories}
if (file.exists("../working_sets") == FALSE) dir.create("../working_sets")
if (file.exists("../working_sets/cv") == FALSE) dir.create("../working_sets/cv")
if (file.exists("../working_sets/train") == FALSE) dir.create("../working_sets/train")
```

### Define sampling function

```{r define sampling function, eval = FALSE}
sampleRows <- function(path, exploreFile, cvFile, p = .4) {
    
    file <- readLines(path, skipNul = TRUE) ## exclude NULL rows
    
    keep <- rbinom(n = length(file), size = 1, prob = p)
    
    efile <- file[keep]
    cvfile <- file[-keep]
    
    write.table(efile, file = exploreFile, row.names = FALSE)
    write.table(cvFile, file = cvfile, row.names = FALSE)
}
```

```{r quiz-1}
# how long is the twitter file?
readLines("../final/en_US/en_US.twitter.txt", skipNul = TRUE) %>% length()

# how large is the blog file?
file.info("../final/en_US/en_US.blogs.txt")$size / 1000000

# who's talking about biostats?
tweet <- readLines("../final/en_US/en_US.twitter.txt", skipNul = TRUE)
tweet[grepl("biostats", tweet)]

# love vs hate
love <- tweet[grepl("love", tweet, fixed = TRUE)]
hate <- tweet[grepl("hate", tweet, fixed = TRUE)]

length(love) / length(hate)

# idiosyncracy
tweet[grep("A computer once beat me at chess, but it was no match for me at kickboxing", tweet)] %>% length()

# who's the longest?
blog <- readLines("../final/en_US/en_US.blogs.txt", skipNul = TRUE)

news <- readLines("../final/en_US/en_US.news.txt", skipNul = TRUE)

chars_blog <- nchar(blog)
max(chars_blog)

chars_news <- nchar(news)
max(chars_news)
```

```{r set up samples}
set.seed(1261992)

my_tweets <- sample(tweet, 200000)
my_blogs  <- sample(blog, 200000)
my_news   <- sample(news, 200000)

saveRDS(my_tweets, "tweets.Rds")
saveRDS(my_blogs, "blogs.Rds")
saveRDS(my_news, "news.Rds")
```

Thinking that I'll just use these subsets to build models in addition to doing EDA. Not sure how much time fitting a model will take, and want to be effecient. I can always just take a new random sample.